name: 'CODE QL Scanning'
on:
   workflow_dispatch:
   push:
jobs:
  code_can:
    runs-on: ubuntu-latest
    name: 'code ql scan'
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: init code ql
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: do scan
        uses: github/codeql-action/analyze@v2
    
