name: 'CODE QL Scanning'
on:
   workflow_dispatch:
   push:
jobs:
  code_can:
    runs-on: ubuntu-latest
    name: 'code ql scan'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run the scan against the codebase
        id: run-scan
        uses: tonys-code-base/run-codeql-analysis-action@master
        with:
          language_to_scan: java
          token: ${{ secrets.GITHUB_TOKEN }}
    
