name: global env vars
on:
  push:
env:
  GLOBAL_VAR: 'GlobalValue' 
jobs:
  log:
    name: sample env var log step
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'Job env var' 
    steps:
    - name: echo env var
      env:
        STEP_VAR: 'Step"s env variable' 

      run: |
        echo ${{ env.GLOBAL_VAR }}
        echo ${{ env.JOB_VAR }}
        echo ${{ env.STEP_VAR }}
