name: "actions getting started 0"
on:
   workflow_dispatch:
   push:
jobs:
    build:
        name: sample build step
        runs-on: ubuntu-latest
        steps:
        - name: checkout and list dirs
          uses: actions/checkout@v3
          run: ls -R
        - name: greeting message 
          run: echo 'hello world actions'
