name: "actions getting started 0"
on: [push,workflow-dispatch]
jobs:
    build:
        name: sample build step
        runs-on: ubuntu-latest
        steps:
            run: echo 'hello world actions'
