name: "actions getting started 2"
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: sample build step
    runs-on: ubuntu-latest
    steps:
      - name: checkout and list dirs
        uses: actions/checkout@v3

      - name: list directories
        run: ls -R

      - name: greeting message 
        run: echo 'hello world actions'

      - name: log branch name
        run: echo "Branch: ${{ github.ref }}"

      - name: conditional step
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "main branch"
