name: Log Branch Name

on: push

jobs:
  log-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Log Branch Name
        run: echo ${{ github.ref }}
      - name: Extract and Log Branch Name
        run: echo "Current Branch: ${{ github.ref##refs/heads/ }}"
